version: '3'
services:
  nginx:
    image: nginx:latest
    environment:
      - "TIMEZONE=Asia/Shanghai"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./${APP_FRONT:-front-local}/admin:/usr/share/nginx/html/admin
      - ./docker/nginx-frontend/servers:/etc/nginx/conf.d
      - ./docker/nginx-frontend/config:/etc/nginx/config
      - ./docker/nginx-frontend/cert:/etc/nginx/cert
    restart: always
    networks:
      - net-itpure-fun

  #node
  node:
    image: node:lts-alpine3.19
    environment:
      - "TIMEZONE=Asia/Shanghai"
    working_dir: "/opt/www"
    volumes:
      - ./${APP_FRONT:-front-local}/web:/opt/www
    ports:
      - "3000:3000"
    entrypoint: ["node", "server/index.mjs"]
    restart: always
    networks:
      - net-itpure-fun

  # 如果是连接到docker内服务，则用服务名称，如:redis
  hyperf:
    image: hyperf/hyperf:8.2-alpine-v3.19-swoole
    environment:
      - "TIMEZONE=Asia/Shanghai"
      - "APP_PROJECT=hyperf"
      - "APP_SYSTEM_ENV=docker"
    working_dir: "/opt/www"
    ports:
      - "9501:9501"
      - "9502:9502"
      - "9503:9503"
    volumes:
      - ./${APP_BACKEND:-itpure-fun}/:/opt/www
    entrypoint: ["php", "watch", "-c"]
    restart: always
    networks:
      - net-itpure-fun

  # 没有将volumes映射出来，需要持久化自行百度一下

  mysql:
    environment:
      - "TZ=Asia/Shanghai"
      - MYSQL_ROOT_PASSWORD=12345678
      - "explicit_defaults_for_timestamp=true"
      - "lower_case_table_names=1"
    volumes:
      - ./docker/mysql/8/my.cnf:/etc/my.cnf
      # - ./docker/mysql/8/data:/var/lib/mysql
      - ./docker/mysql/8/logs:/var/log/mysql
      - ./docker/mysql/db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - 3306:3306
    image: mysql:8
    restart: always
    networks:
      - net-itpure-fun
    # command: "--default-authentication-plugin=mysql_native_password"
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - net-itpure-fun
  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "4369:4369"
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    environment:
      - RABBITMQ_DEFAULT_USER=itpurefun
      - RABBITMQ_DEFAULT_PASS=123456
    networks:
      - net-itpure-fun
networks:
  net-itpure-fun:
    driver: bridge